version: "3.9"
services:
  db:
    image: "postgres:${POSTGRES_VERSION}"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    networks:
      - payments

volumes:
  db:
    driver: local

networks:
  payments:
    driver: bridge
